language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  matrix:
    - CARGO_ARGS="--no-default-features"
    - CARGO_ARGS="--no-default-features --features=glium"
    # SDL can't be easily tested, sadly :(
script:
  # FIXME: Run tests of all local crates
  - |
      echo "rust is: $TRAVIS_RUST_VERSION" &&
      travis-cargo build -- $CARGO_ARGS &&
      travis-cargo --only beta doc -- -p breeze_core
after_success:
  - travis-cargo doc-upload
  # FIXME: This doesn't work :(
