language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
script: cargo build --no-default-features --features=glium
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo build -- --no-default-features --features=glium &&
      travis-cargo --only stable doc -- -p breeze_core
after_success:
  - travis-cargo --only stable doc-upload
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
