[package]
name = "sneeze"
version = "0.1.0"
authors = ["Jonas Schievink <jonas@schievink.net>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
sdl2 = "0.9"
arrayvec = "0.3"

[dependencies.glium]
version = "0.10"
optional = true
features = ["glutin"]
default-features = false
