[package]
name = "breeze"
version = "0.1.0"
authors = ["Jonas Schievink <jonas@schievink.net>"]
license = "Apache-2.0/MIT"

[dependencies]
breeze_core = { path = "breeze_core" }
breeze_frontends = { path = "breeze_frontends" }
breeze_frontend_api = { path = "breeze_frontend_api" }
libsavestate = { path = "libsavestate" }
log = "0.3"
env_logger = "0.3"
lazy_static = "0.1"
# clap comes with a few optional features we don't really need (colored output
# and command correction)
clap = { version = "1.4", default-features = false }

[features]
# reexport frontends
default = ["sdl"]
sdl = ["breeze_frontends/sdl2"]
glium = ["breeze_frontends/glium"]
