[package]
name = "sneeze"
version = "0.1.0"
authors = ["Jonas Schievink <jonas@schievink.net>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
arrayvec = "0.3"
lazy_static = "0.1"

[dependencies.glium]
version = "0.10"
optional = true
features = ["glutin"]
default-features = false

[dependencies.sdl2]
version = "0.9"
optional = true

[features]
default = ["sdl2"]

[profile.dev]
opt-level = 2
