[package]
name = "byte_array"
description = "Utility macro for creating convenient fixed-size `u8` arrays."
version = "0.1.0"
authors = ["Jonas Schievink <jonas@schievink.net>"]

[lib]
path = "lib.rs"
