[package]
name = "breeze_frontend_api"
description = "Breeze Emulator Frontend API"
version = "0.1.0"
authors = ["Jonas Schievink <jonas@schievink.net>"]
license = "Apache-2.0/MIT"

[lib]
path = "lib.rs"

[dependencies]
libsavestate = { path = "../libsavestate" }
