[package]
name = "libsavestate"
description = "A crate for easy implementation of emulator save states"
version = "0.1.0"
authors = ["Jonas Schievink <jonas@schievink.net>"]
license = "Apache-2.0/MIT"

[lib]
path = "lib.rs"
